export const SIGNIN_FAILURE = 'AUTHENTICATION/SIGNIN_FAILURE';
export const SIGNIN_REQUEST = 'AUTHENTICATION/SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'AUTHENTICATION/SIGNIN_SUCCESS';

export const SIGNOUT_REQUEST = 'AUTHENTICATION/SIGNOUT_REQUEST';
export const SIGNOUT_SUCCESS = 'AUTHENTICATION/SIGNOUT_SUCCESS';
