export const RECEIVE_USER_SIGN_IN_FAILURE = 'AUTHENTICATION/RECEIVE_USER_SIGN_IN_FAILURE';
export const RECEIVE_USER_SIGN_IN_SUCCESS = 'AUTHENTICATION/RECEIVE_USER_SIGN_IN_SUCCESS';
export const REQUEST_USER_SIGN_IN = 'AUTHENTICATION/REQUEST_USER_SIGN_IN';

export const REQUEST_USER_SIGN_OUT = 'AUTHENTICATION/REQUEST_USER_SIGN_OUT';
