export const RECEIVE_USER_SIGN_UP_FAILURE = 'AUTHENTICATION/RECEIVE_USER_SIGN_UP_FAILURE';
export const RECEIVE_USER_SIGN_UP_SUCCESS = 'AUTHENTICATION/RECEIVE_USER_SIGN_UP_SUCCESS';
export const REQUEST_USER_SIGN_UP = 'AUTHENTICATION/REQUEST_USER_SIGN_UP';

export const REQUEST_USER_SIGN_OUT = 'AUTHENTICATION/REQUEST_USER_SIGN_OUT';
