require: rubocop-rspec

AllCops:
  TargetRubyVersion: '2.5'
  Exclude:
    - db/schema.rb
    - bin/**/*
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/**/*

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
