require: rubocop-rspec

AllCops:
  TargetRubyVersion: '2.4'
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'config/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
