require: rubocop-rspec

AllCops:
  TargetRubyVersion: '2.4'
  Exclude:
    - db/schema.rb
    - bin/**/*
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/**/*

RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*

RSpec/NestedGroups:
  Max: 5

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false
