language: ruby
cache:
  bundler: true
  yarn: true

rvm:
  - 2.4.1

node_js:
  - 7.10.0

sudo: required
dist: trusty
addons:
  postgresql: '9.6'

services:
  - postgresql

notifications:
  email: false

before_install:
  - nvm install 7.10.0
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - bundle install
  - yarn install

script:
  - script/cibuild

env:
  global:
    RAILS_ENV=test
