language: ruby
cache:
  bundler: true
  directories:
    - client/node_modules

rvm:
  - 2.4.2

node_js:
  - 8.7.0

sudo: required
dist: trusty
addons:
  postgresql: '9.6'

services:
  - postgresql

notifications:
  email: false

before_install:
  - nvm install 8.7.0
  - nvm use 8.7.0

install:
  - bundle install
  - (cd client && npm install)

script:
  - script/cibuild

env:
  global:
    RAILS_ENV=test
