shared: &shared
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default: &default
  <<: *shared
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: some_schedules_development

test:
  <<: *default
  database: some_schedules_test

production:
  <<: *shared
  url: <%= ENV['DATABASE_URL'] %>
