#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew update
  brew tap homebrew/bundle 2>/dev/null

  brew bundle check 2>&1 >/dev/null || {
    echo "==> Installing Homebrew dependencies..."
    brew bundle
  }
fi

if ! ruby --version | grep --quiet 2.5.0; then
  echo "==> Installing rbenv and ruby 2.5.0..."

  rbenv install 2.5.0
  gem install bundler
fi

echo "==> Installing mix dependencies..."
bundle install
