#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

if ! docker-compose ps | grep --silent some_schedules; then
  echo "==> Starting postgres..."

  docker-compose up -d
fi

echo "==> Setting up database..."
bin/rails db:reset

echo "==> App is now ready to go!"
