export const RECEIVE_COMPANY_CREATION_FAILURE = 'COMPANIES/RECEIVE_COMPANY_CREATION_FAILURE';
export const RECEIVE_COMPANY_CREATION_SUCCESS = 'COMPANIES/RECEIVE_COMPANY_CREATION_SUCCESS';
export const REQUEST_COMPANY_CREATION = 'COMPANIES/REQUEST_COMPANY_CREATION';
