export const RECEIVE_COMPANIES_BY_USER_ID_FAILURE = 'COMPANIES/RECEIVE_COMPANIES_BY_USER_ID_FAILURE';
export const RECEIVE_COMPANIES_BY_USER_ID_SUCCESS = 'COMPANIES/RECEIVE_COMPANIES_BY_USER_ID_SUCCESS';
export const REQUEST_COMPANIES_BY_USER_ID = 'COMPANIES/REQUEST_COMPANIES_BY_USER_ID';

export const RECEIVE_COMPANY_CREATION_FAILURE = 'COMPANIES/RECEIVE_COMPANY_CREATION_FAILURE';
export const RECEIVE_COMPANY_CREATION_SUCCESS = 'COMPANIES/RECEIVE_COMPANY_CREATION_SUCCESS';
export const REQUEST_COMPANY_CREATION = 'COMPANIES/REQUEST_COMPANY_CREATION';
