export const RECEIVE_USER_BY_ID_FAILURE = 'USERS/RECEIVE_USER_BY_ID_FAILURE';
export const RECEIVE_USER_BY_ID_SUCCESS = 'USERS/RECEIVE_USER_BY_ID_SUCCESS';
export const REQUEST_USER_BY_ID = 'USERS/REQUEST_USER_BY_ID';

export const RECEIVE_USER_SIGN_UP_FAILURE = 'USERS/RECEIVE_USER_SIGN_UP_FAILURE';
export const RECEIVE_USER_SIGN_UP_SUCCESS = 'USERS/RECEIVE_USER_SIGN_UP_SUCCESS';
export const REQUEST_USER_SIGN_UP = 'USERS/REQUEST_USER_SIGN_UP';
