export const RECEIVE_USER_SIGN_UP_FAILURE = 'USERS/RECEIVE_USER_SIGN_UP_FAILURE';
export const RECEIVE_USER_SIGN_UP_SUCCESS = 'USERS/RECEIVE_USER_SIGN_UP_SUCCESS';
export const REQUEST_USER_SIGN_UP = 'USERS/REQUEST_USER_SIGN_UP';
